apiVersion: v1
kind: Service
metadata:
  labels:
    app: manageemployees-dplmnt
  name: manageemployees-svc
  namespace: default
spec:
  clusterIP: 10.43.236.145
  clusterIPs:
  - 10.43.236.145
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30657
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: manageemployees-dplmnt
  sessionAffinity: None
  type: NodePort
